### ISSUE TITLE
Pravega sample streamCutsCli prompt is terminating while giving streams/events/both value as 0 in SAMPLE option

### ISSUE THREAD

**Issue by Ranjan-Padhi** [pravega/pravega-samples#201]
* Starting Pravega benchmark sample `streamCutsCli` script with SAMPLE option.
* while asking streams and events value, just passing 0 value in both or in any one of the streams or events.

OutPut:-
Instead of giving proper error message, its displaying below exception and exit from streamCutsExamples prompt

NOTE :- Same scenario is working properly while doing with `streamCutsCli` script with TIMESERIES option, its displaying proper error message

Exception :-
```
streamCutsExamples >simple
**** You have selected a simple example to see how Pravega StreamCuts work. Great choice!!
**** Now, we will ask you some questions to set up the example:

**** How many streams do you want to create? (e.g., from 1 to 5):
simple_example > 0
**** How many events per stream do you want to create? (e.g., from 1 to 20):
simple_example > 12

**** Your Streams are ready :)

**** Now, to see how StreamCuts work, we are going to build them!
Exception in thread "main" java.lang.IllegalArgumentException: Stream names that the reader group can read from cannot be empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at io.pravega.client.stream.ReaderGroupConfig$ReaderGroupConfigBuilder.build(ReaderGroupConfig.java:182)
        at io.pravega.example.streamcuts.StreamCutsCli.doBoundedPrinting(StreamCutsCli.java:177)
        at io.pravega.example.streamcuts.StreamCutsCli.doSimpleExample(StreamCutsCli.java:151)
        at io.pravega.example.streamcuts.StreamCutsCli.processCommand(StreamCutsCli.java:107)
        at io.pravega.example.streamcuts.StreamCutsCli.run(StreamCutsCli.java:69)
        at io.pravega.example.streamcuts.StreamCutsCli.main(StreamCutsCli.java:299)
#
```

**Comment by RaulGracia** [comment]
Closed via #251.
